# Generated by Django 5.0.3 on 2024-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0003_about_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='president',
            field=models.ImageField(default='default_president.jpg', upload_to='president_images'),
        ),
    ]
