# Generated by Django 5.0.3 on 2024-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0004_message_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default='none', upload_to='president_images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='president',
            field=models.ImageField(default='none', upload_to='president_images'),
        ),
    ]
