# Generated by Django 5.0.3 on 2024-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('father', models.CharField(max_length=40)),
                ('date', models.IntegerField(max_length=10)),
                ('dep', models.CharField(max_length=40)),
                ('year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year'), ('Master First Year', 'Master First Year'), ('Master Second Year', 'Master Second Year')], max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField(max_length=12)),
                ('file', models.ImageField(default='none', upload_to='president_images')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
