# Generated by Django 5.0.3 on 2024-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0007_membership_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='year',
            field=models.CharField(max_length=40),
        ),
    ]
