# Generated by Django 5.0.3 on 2024-03-16 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0009_alter_contact_phone_alter_membership_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{2}[-\\/]\\d{2}[-\\/]\\d{4}$', 'Date format must be MM-DD-YYYY or MM/DD/YYYY')]),
        ),
    ]
