# Generated by Django 5.0.3 on 2024-03-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0011_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='phone',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
