# Generated by Django 5.0.3 on 2024-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0012_alter_notes_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='semester',
            field=models.CharField(max_length=40),
        ),
    ]
