# Generated by Django 5.0.3 on 2024-03-19 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0013_alter_notes_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('amount', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
