# Generated by Django 5.0.3 on 2024-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0014_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='file',
            field=models.ImageField(default='none', upload_to='media/president_images'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(default='none', upload_to='Notes'),
        ),
    ]
