# Generated by Django 5.0.3 on 2024-03-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0015_alter_membership_file_alter_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='teacher',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
