# Generated by Django 5.0.3 on 2024-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0016_notes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='file',
            field=models.ImageField(default='none', upload_to='media/members_images'),
        ),
    ]
