# Generated by Django 5.0.3 on 2024-03-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0017_alter_membership_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='file',
            field=models.ImageField(default='none', upload_to='members_images'),
        ),
    ]
