# Generated by Django 5.0.3 on 2024-03-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0019_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q9',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='time',
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=50)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nizam.survey')),
            ],
        ),
    ]
