# Generated by Django 5.0.3 on 2024-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0022_remove_survey_opt1_remove_survey_opt2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='survey',
            name='opt1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='opt2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
