# Generated by Django 5.0.3 on 2024-03-26 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0025_notes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='survey',
            name='opt1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='opt2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
