# Generated by Django 5.0.3 on 2024-03-26 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0029_alter_notes_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
