# Generated by Django 5.0.3 on 2024-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0030_alter_notes_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
