# Generated by Django 5.0.3 on 2024-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0031_alter_notes_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='opt2',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
