# Generated by Django 5.0.3 on 2024-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0032_remove_survey_opt1_remove_survey_opt2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=3),
        ),
    ]
