# Generated by Django 5.0.3 on 2024-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0033_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='opt1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='opt2',
            field=models.BooleanField(default=False),
        ),
    ]
