# Generated by Django 5.0.3 on 2024-03-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0034_remove_question_answer_question_opt1_question_opt2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='opt1',
            new_name='No',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='opt2',
            new_name='yes',
        ),
    ]
