# Generated by Django 5.0.3 on 2024-04-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0036_rename_no_question_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='no',
            new_name='ans',
        ),
        migrations.RemoveField(
            model_name='question',
            name='yes',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
    ]
