# Generated by Django 5.0.3 on 2024-04-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0037_rename_no_question_ans_remove_question_yes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='no',
        ),
        migrations.AddField(
            model_name='question',
            name='yes',
            field=models.BooleanField(default=False),
        ),
    ]
