# Generated by Django 5.0.3 on 2024-04-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0038_rename_ans_question_no_question_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
    ]
