# Generated by Django 5.0.3 on 2024-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0041_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
