# Generated by Django 5.0.3 on 2024-04-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0044_delete_donation_result_dept_result_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
