# Generated by Django 5.0.3 on 2024-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0046_questions_remove_result_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AddField(
            model_name='questions',
            name='sno',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
