# Generated by Django 5.0.3 on 2024-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nizam', '0051_datasurvey_delete_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSurvey',
            new_name='Data',
        ),
    ]
